#server:
 # port: 8080
##
#datasource:
 #   url: jdbc:postgresql://localhost:26258/converse
  #  username: nahara
   # password:root
#spring.jpa:
 #       hibernate.ddl-auto: auto-update
  #      show-sql: true